# Generated by Django 5.2.6 on 2025-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
